general:
    log: {level: INFO, filename: null, filemode: null, format: null, datefmt: null}
    outdir: ./Fornax_A
    n_jobs: 1
    datasets_file: Fornax_A/datasets/datasets.yaml
    models_file: Fornax_A/datasets/models.yaml
    config_file: null
    analysis_path: null
roi:
    target:
        name: Fornax A
        position: {frame: icrs, lon: 50.67412083 deg, lat: -37.2082 deg}
        model: {}
    radius: 0.5 deg
    catalogs: all
    dict_sep:
        3FGL J0322.5-3721:
            position: {lon: 50.642601013183594 deg, lat: -37.3583984375 deg, frame: icrs}
            separation: 0.15227774978244435
        4FGL J0322.6-3712e:
            position: {lon: 50.66999816894531 deg, lat: -37.209999084472656 deg, frame: icrs}
            separation: 0.003744008226996352
        3FHL J0322.6-3712e:
            position: {lon: 50.66999816894531 deg, lat: -37.209999084472656 deg, frame: icrs}
            separation: 0.003744008226996352
energy_range: {min: null, max: null}
plot:
    leg_style: {}
